"""添加消息转发功能字段

Revision ID: 119f973347b5
Revises: 6b3426b07136
Create Date: 2025-07-27 16:30:01.343153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119f973347b5'
down_revision = '6b3426b07136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.Enum('member', 'admin', name='channel_member_role'), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uix_channel_user')
    )
    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_members_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_members_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'file', name='message_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_forwarded', sa.Boolean(), nullable=False),
    sa.Column('original_message_id', sa.Integer(), nullable=True),
    sa.Column('original_channel_id', sa.Integer(), nullable=True),
    sa.Column('original_user_id', sa.Integer(), nullable=True),
    sa.Column('forward_comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['original_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_original_message_id'), ['original_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_reply_to_id'), ['reply_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'reaction', name='uix_message_user_reaction')
    )
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))

    op.drop_table('message_reactions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_id'))
        batch_op.drop_index(batch_op.f('ix_messages_original_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_channel_id'))

    op.drop_table('messages')
    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_members_channel_id'))

    op.drop_table('channel_members')
    # ### end Alembic commands ###
