"""频道分类与类型支持

Revision ID: 6b3426b07136
Revises: f5280c47fb82
Create Date: 2025-07-26 21:44:42.891318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3426b07136'
down_revision = 'f5280c47fb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_server_id'), ['server_id'], unique=False)

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Enum('text', 'voice', 'video', 'announcement', name='channel_type'), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_channels_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_server_id'), ['server_id'], unique=False)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_channels_server_id'))
        batch_op.drop_index(batch_op.f('ix_channels_category_id'))
        batch_op.drop_column('icon')
        batch_op.drop_column('description')
        batch_op.drop_column('type')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_server_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
