version: '3.8'

services:
  yoto-api:
    image: docker.io/U2SG/yoto:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.role == worker
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    networks:
      - yoto-network
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  yoto-celery-worker:
    image: docker.io/U2SG/yoto:latest
    command: celery -A yoto_backend.celery worker --loglevel=info
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    networks:
      - yoto-network

  yoto-celery-beat:
    image: docker.io/U2SG/yoto:latest
    command: celery -A yoto_backend.celery beat --loglevel=info
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    networks:
      - yoto-network

networks:
  yoto-network:
    driver: overlay
    attachable: true 